# Generated by Django 5.2.14 on 2026-05-12 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='quantidade',
        ),
    ]
