# Generated by Django 5.2.14 on 2026-05-13 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_equipamento_quantidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='finalidade',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='laboratorio',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='equipamento',
        ),
        migrations.AddField(
            model_name='reserva',
            name='equipamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='inventario.equipamento'),
            preserve_default=False,
        ),
    ]
