# Generated by Django 5.2.14 on 2026-05-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_remove_reserva_finalidade_remove_reserva_laboratorio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='data_devolucao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
